// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLCXm7BxWIjoPvQS85lULCPTOap84iqU4',
    appId: '1:1040544126628:web:546a4c2b22d6e581327831',
    messagingSenderId: '1040544126628',
    projectId: 'chatapp-2ac09',
    authDomain: 'chatapp-2ac09.firebaseapp.com',
    storageBucket: 'chatapp-2ac09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbi60qyZwg57cBshh7Os8uSAJ5q8-kLkU',
    appId: '1:1040544126628:android:2931d78e9d7edde3327831',
    messagingSenderId: '1040544126628',
    projectId: 'chatapp-2ac09',
    storageBucket: 'chatapp-2ac09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9PF1Rdud-89jrnIdmpgyEu9T6P7Jctc',
    appId: '1:1040544126628:ios:868aec728e7d65ca327831',
    messagingSenderId: '1040544126628',
    projectId: 'chatapp-2ac09',
    storageBucket: 'chatapp-2ac09.appspot.com',
    iosBundleId: 'com.example.firebasechataap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb9PF1Rdud-89jrnIdmpgyEu9T6P7Jctc',
    appId: '1:1040544126628:ios:14231044d8a81529327831',
    messagingSenderId: '1040544126628',
    projectId: 'chatapp-2ac09',
    storageBucket: 'chatapp-2ac09.appspot.com',
    iosBundleId: 'com.example.firebasechataap.RunnerTests',
  );
}
